$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:4
        },
        320:{
            items:4
        },
        600:{
            items:4
        },
        1024:{
            items:4
        },
        1440:{
            items:6
        },
        2560:{
            items:5
        },
        425:{
            items:4
        },
        768:{
            items:5
        },
        375:{
            items:4
        },
        820:{
            items:5
        },
        912:{
            items:5
        },
        540:{
            items:5
        },
    }
})